name: express gcp stack
description: This stack sets up a express app and deploys it to GCP.
branding:
  icon: cloud
  color: blue

inputs:
  - name: workload_identity_provider
    type: string
    required: true
  - name: service_account
    type: string
    required: true
  - name: audience
    type: string
    required: true

configs:
  repo-metadata:
    parameters:
      description: An express app on google app engine.
      topics:
        - NodeJS
        - Express
        - App Engine
  
  security:
parameters:
      vulnerability-alerts: true
      automated-security-fixes: true

init:
 uses: stack-init.yml
